### ISSUE TITLE
Add support for `Unitful` 

### ISSUE THREAD

**Issue by Sbozzolo** [CliMA/ClimaAnalysis.jl#53]
[Unitful.jl](https://github.com/PainterQubits/Unitful.jl) is a package that handles physical units. It would be interesting to explore a possible integration with `ClimaAnalysis`.

**Comment by AlexisRenchon** [comment]
I haven't made any functionality or modules for it, but I did some stuff in [ClimaLandSimulations here](https://github.com/CliMA/ClimaLand.jl/blob/main/lib/ClimaLandSimulations/src/Fluxnet/fluxnet_utilities/inputs_dataframe.jl) 

```jl

# inside Fluxnet.jl module
using Unitful: R, L, mol, K, kJ, °C, m, g, cm, hr, mg, s, μmol, Pa, W, mm, kPa
using UnitfulMoles: molC
using Unitful, UnitfulMoles

# Register Fluxnet with Unitful.jl
function __init__()
    Unitful.register(Fluxnet)
end

    # inside inputs_dataframe.jl
    # make a Unitful dataframe with SI units and one with commonly used units
    columns = variables_name[2:end]
    units = [
        molCO₂ * m^-2 * s^-1,
        K,
        Pa,
        Pa,
        m * s^-1,
        m * s^-1,
        W * m^-2,
        W * m^-2,
        molCO₂,
        m^3 * m^-3,
        K,
        molCO₂ * m^-2 * s^-1,
        W * m^-2,
        W * m^-2,
        W * m^-2,
        W * m^-2,
    ]
    inputs_SI = copy(inputs)
    foreach(
        (col, unit) -> inputs_SI[!, col] .= first([inputs_SI[!, col]]unit),
        columns,
        units,
    )

    units_to = [
        μmolCO₂ * m^-2 * s^-1,
        °C,
        kPa,
        Pa,
        mm * s^-1,
        m * s^-1,
        W * m^-2,
        W * m^-2,
        μmolCO₂,
        m^3 * m^-3,
        °C,
        μmolCO₂ * m^-2 * s^-1,
        W * m^-2,
        W * m^-2,
        W * m^-2,
        W * m^-2,
    ]
    inputs_commonly_used = copy(inputs_SI)
    foreach(
        (col, unit_to) ->
            inputs_commonly_used[!, col] =
                uconvert.(unit_to, inputs_SI[!, col]),
        columns,
        units_to,
    )
```

**Comment by AlexisRenchon** [comment]
and also in [ParamViz](https://github.com/CliMA/ParamViz.jl/blob/main/src/generate_fig.jl)

**Comment by AlexisRenchon** [comment]
This makes me think: 
we currently give units with implicit multiplication (e.g., `m s^-1`, without `*`), which is not compatible with unitful convention, but I guess that's an easy conversion so not a problem?

**Comment by Sbozzolo** [comment]
It would not be a bad idea to require units to be formatted like that, it would make them parsable by other programs as well.

**Comment by AlexisRenchon** [comment]
there's other unitful / unitfulmoles conventions, e.g., molCO2 (not mol CO2, no space), kPa (but I guess we usually don't have multiplier indices)
